align_depth: True
initial_reset: False
enable_infra1: False
enable_infra2: False
filters: 'spatial,temporal,pointcloud'
clip_distance: 3.0
color_width: 848
color_height: 480
color_fps: 60.0
depth_width: 848
depth_height: 480
depth_fps: 90.0
enable_pointcloud: True
dense_pointcloud: True
enable_sync: True
device_type: 'd455'
rgb_camera: {
    auto_exposure_priority: True,
    backlight_compensation: True,
    enable_auto_exposure: True,
    enable_auto_white_balance: True,
    frames_queue_size: 16,
    power_line_frequency: 1,
    saturation: 71,
    sharpness: 74,
    }
stereo_module:
    emitter_always_on: False
    emitter_enabled: 2
    emitter_on_off: False
    enable_auto_exposure: True
    error_polling_enabled: True
    frames_queue_size: 16
    inter_cam_sync_mode: 0
    laser_power: 150.0
    visual_preset: 3
temporal:
    filter_smooth_alpha: 0.14
    filter_smooth_delta: 37
    frames_queue_size: 16
    holes_fill: 6
spatial:
    filter_magnitude: 3
    filter_smooth_alpha: 0.54
    filter_smooth_delta: 11
    holes_fill: 3
    frames_queue_size: 16
pointcloud:
    stream_filter: 2
    stream_format_filter: 6
    frames_queue_size: 16
    filter_magnitude: 2
allow_no_texture_points: False