align_depth: True
initial_reset: False
enable_infra1: False
enable_infra2: False
# filters: 'spatial,temporal,pointcloud'
clip_distance: 2.0
color_width: 848
color_height: 480
color_fps: 15.0
depth_width: 848
depth_height: 480
depth_fps: 15.0
enable_pointcloud: True
dense_pointcloud: True
enable_sync: True
device_type: 'd455'


allow_no_texture_points: False